---
title: "Correct_colony_depths"
author: "Melissa Naugle"
date: "18/04/2022"
output: html_document
---


This script shows how depths on "Coral colony metadata from the ECT1_RRAP_2023_11_16_AhyaCh1.xlsx" were calculated 

Written by Hugo Denis and Melissa Naugle

```{r setup, include=F}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(readxl)
rm( list = ls())
date = Sys.Date()
setwd("/Users/Melissa/Desktop/GitHub/Ahya_heat_tol_variation/Rscripts_dataprocessing/")

```

#Load data
```{r warning=F}
#Colony data
colony_metadata <- read_xlsx("../Rawdata/Coral colony metadata from the ECT1_RRAP_2023_11_16_AhyaCh1.xlsx", sheet = 2) %>% dplyr::select(1:31) %>% rename(depthcheck = depthOfColonyinMetersCorrected)

colony_metadata <- colony_metadata %>% mutate(timeOfDay = strptime(timeOfDay, format="%Y-%m-%d %H:%M:%S"))
colony_metadata$timeOfDay <- format(colony_metadata$timeOfDay , "%H:%M:%S")

colony_metadata$depthOfColonyinMeters[colony_metadata$depthOfColonyinMeters == "~2.5-3.5"] <- 3
colony_metadata$depthOfColonyinMeters[colony_metadata$depthOfColonyinMeters == "~5"] <- 5
colony_metadata$depthOfColonyinMeters[colony_metadata$depthOfColonyinMeters == "~3"] <- 3
colony_metadata$depthOfColonyinMeters[colony_metadata$depthOfColonyinMeters == "~<2"] <- 1.5

colony_metadata$Collection.date <- as.Date(paste0(colony_metadata$yearCollected,"-",colony_metadata$monthCollected,"-",colony_metadata$dayCollected))
colony_metadata$Time <- as.POSIXct(paste0(colony_metadata$yearCollected,"-",colony_metadata$monthCollected,"-",colony_metadata$dayCollected," ",colony_metadata$timeOfDay),format="%Y-%m-%d %H:%M:%S")

#tide data
tide<-read.csv("../Rawdata/TideData.csv")

#Merge the two tables
colonies_metadata<-merge(colony_metadata,tide, by = c("locationID", "yearCollected", "monthCollected", "dayCollected"))


#Convert times to POSIXct
colonies_metadata[,c("Time1","Time2","Time3","Time4")]<-lapply(colonies_metadata[,c("Time1","Time2","Time3","Time4")],
       function(x)as.POSIXct(paste(colonies_metadata$Collection.date,x,sep=" "),format="%Y-%m-%d %H:%M"))
#Correct the depth through linear interpolation of the tide 
#at the time of collection
colonies_metadata$Tide_adjust <- 0

```

#adjust depths to tides 
```{r }

colonies_metadata2 <- colonies_metadata %>% filter(!(depthOfColonyinMeters == "NA"))

for(i in 1:nrow(colonies_metadata2)){

  #Avoid missing values
  if(!is.na(colonies_metadata2$depthOfColonyinMeters[i])){
#Take into account the case where time of sampling equals one of tide times   
      if(colonies_metadata2[i,"Time"] %in% c(colonies_metadata2[i,"Time1"],colonies_metadata2[i,"Time2"],colonies_metadata2[i,"Time3"],colonies_metadata2[i,"Time4"])){
        id_equal=which(c(colonies_metadata2[i,"Time1"],colonies_metadata2[i,"Time2"],colonies_metadata2[i,"Time3"],colonies_metadata2[i,"Time4"])==colonies_metadata2[i,"Time"])
        colonies_metadata2$Tide_adjust[i]=colonies_metadata2[i,paste0("Level",as.character(id_equal))] 
      }else{
          #Find Highest/Lowest tide flanking time of collection
      id_inf=max(which(c(colonies_metadata2[i,"Time1"],colonies_metadata2[i,"Time2"],colonies_metadata2[i,"Time3"],colonies_metadata2[i,"Time4"])<colonies_metadata2[i,"Time"]))
      id_sup=min(which(c(colonies_metadata2[i,"Time1"],colonies_metadata2[i,"Time2"],colonies_metadata2[i,"Time3"],colonies_metadata2[i,"Time4"])>colonies_metadata2[i,"Time"]))
      time_inf=paste0("Time",as.character(id_inf))
      time_sup=paste0("Time",as.character(id_sup))
      level_inf=paste0("Level",as.character(id_inf))
      level_sup=paste0("Level",as.character(id_sup))
      
      #Find parameters of sinusoid curve passing through those 2 points
      diff=(colonies_metadata2[i,level_inf]-colonies_metadata2[i,level_sup])
      #Amplitude
      A=abs(diff/2)
      #Period
      b=pi/as.numeric(difftime(colonies_metadata2[i,time_sup], colonies_metadata2[i,time_inf], units = "min"))
      #Phase
      c=as.numeric(difftime(colonies_metadata2[i,if_else(diff>0,time_inf,time_sup)],as.POSIXct(paste0(format(colonies_metadata2[i,c("Time1")],format="%Y-%m-%d")," ","00:00:00"),format="%Y-%m-%d %H:%M:%S"),units="min"))-pi/(2*b)
      #Vertical Shift
      d=(colonies_metadata2[i,level_inf]+colonies_metadata2[i,level_sup])/2
      
      #Find tide height at the time of collection
      timemin=as.numeric(difftime(colonies_metadata2[i,"Time"],as.POSIXct(paste0(format(colonies_metadata2[i,c("Time1")],format="%Y-%m-%d")," ","00:00:00"),format="%Y-%m-%d %H:%M:%S"),units="min"))
      y=A*sin(b*(timemin-c))+d
  
      colonies_metadata2$Tide_adjust[i]=y
      } 
  } else {
    colonies_metadata2$Tide_adjust[i]=NA
  }
  
}

#correct depth with the tide 
colonies_metadata2$Depth_corrected <- round(as.numeric(colonies_metadata2$depthOfColonyinMeters)-colonies_metadata2$Tide_adjust,1)
```

#account for colonies without depths and fix naming 
```{r }
nodepths <- anti_join(colonies_metadata,colonies_metadata2, by = "individualID") %>% mutate(Depth_corrected = NA)

colonies_metadata <- rbind(colonies_metadata2,nodepths)
colonies_metadata$Site_year[colonies_metadata$Site_year == "North Direction_2021"] <- "North Direction-natbleach_2021"
colonies_metadata$Site <- sapply(strsplit(colonies_metadata[,44],"_"), `[`, 1)
colonies_metadata$Site.name <- sapply(strsplit(colonies_metadata[,43],"-"), `[`, 1)
colonies_metadata$Genotype <- readr::parse_number(sapply(strsplit(colonies_metadata[,6],"_"), `[`, 2))

#fix naming
colonies_metadata$Site[colonies_metadata$Site == "Fitzroy Island"] <- "Fitzroy"
colonies_metadata$Site_year[colonies_metadata$Site_year == "Fitzroy Island_2021"] <- "Fitzroy_2021"

#make site_geno_year variable 
colonies_metadata$Site_geno_year <- paste0(colonies_metadata$Site,"_",colonies_metadata$Genotype,"_",colonies_metadata$yearCollected)

#choose only original colonies 
colonies_metadata <- colonies_metadata %>% filter(resampled == "N")

#fix naming
colonies_metadata$Site.name[colonies_metadata$Site.name == "EastCay"] <- "East Cay"
colonies_metadata$Site.name[colonies_metadata$Site.name == "LadyMusgrave"] <- "Lady Musgrave"
colonies_metadata$Site.name[colonies_metadata$Site.name == "NorthDirection"] <- "North Direction"
colonies_metadata$Site.name[colonies_metadata$Site.name == "StCrispin"] <- "St Crispin"
colonies_metadata$Site.name[colonies_metadata$Site.name == "NoName"] <- "No Name"

colonies_metadata$check = round(as.numeric(colonies_metadata$depthcheck), digits = 3) - round(colonies_metadata$Depth_corrected, digits = 3)
colonies_metadata[colonies_metadata$check != 0,]
#all matched up 

```






